server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/tonitingaurav/configuration
          search-paths:
          - employee-management
          - asset-management